[env]
UV_NATIVE_TLS = "true"

[tools]
uv = "latest"
ruby = "3.3"
python = "3.12"
swiftformat = "latest"
swiftlint = "latest"
bun = "latest"
node = "latest"

"pipx:csvkit" = "latest"
"pipx:git-filter-repo" = "latest"
"pipx:google-cloud-aiplatform" = "latest"
"pipx:httpie" = "latest"
"pipx:black" = "latest"
"pipx:jc" = "latest"
"pipx:things-cli" = "latest"
"pipx:yt-dlp" = "latest"

"npm:fx" = "latest"
"npm:fast-cli" = "latest"
"npm:appium" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"

"npm:@sentry/cli" = "latest"

"pipx:llm" = { version = "latest", uvx_args = "--with llm-anthropic,llm-gemini,llm-jq,llm-cmd,llm-cmd-comp --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org" }
# "pipx:llm" = { version = "latest", uvx_args = "--with llm-openai,llm-anthropic,llm-gemini,llm-jq,llm-cmd,llm-cmd-comp" }
"pipx:files-to-prompt" = "latest"
"pipx:chunkhound" = "latest"

"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@nova-mcp/mcp-nova" = "latest"

"npm:@mariozechner/pi-coding-agent" = "latest"

"npm:opencode-ai" = "latest"
"npm:openskills" = "latest"
"npm:opencode-openai-codex-auth" = "latest"
"npm:btca" = "latest" # opencode/micode

"github:Ryu0118/xcstrings-crud" = "latest"

"github:davidfowl/tally" = "latest"

[settings]
experimental = true
pipx.uvx = true
npm.bun = true
vfox = false
idiomatic_version_file_enable_tools = ["ruby", "python", "node"]

trusted_config_paths = [
    '~/Projects',
    '~/.superset/worktrees/'
]
